version: "3.8"
services:
  node:
    image: node:latest
    volumes:
      - ./:/src
    tty: true
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:tpc-cdn.flibus.team"
      - "traefik.basic.port=3000"

networks:
  web:
    external: true

