version: "3.8"
services:
  neo:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo/data:/data
      - ./neo/log:/log
      - ./neo/import:/var/lib/neo4j/import
      - ./neo/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/b1otope
  node:
    image: node:latest
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./../node:/src
    tty: true
  mercure:
    image : dunglas/mercure
    volumes:
      - ./mercure/caddy:/etc/caddy
    ports:
      - "8081:80"
      - "443:443"
    environment:
      - SERVER_NAME=localhost
      - MERCURE_SUBSCRIBER_JWT_KEY=changeIt
      - MERCURE_PUBLISHER_JWT_KEY=changeIt
      - CORS_ALLOWED_ORIGINS=*
      - ALLOW_ANONYMOUS=1
    command: ['caddy' ,'run' , '-config',  '/etc/caddy/Caddyfile']