version: "3.8"
services:
  neo:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo/data:/data
      - ./neo/log:/log
      - ./neo/import:/var/lib/neo4j/import
      - ./neo/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/b1otope
  node:

    build: ./node
    ports:
      - "8000:8000"
      - "8080:8081"
    volumes:
      - ./../node:/src
      - ./../front:/front
    tty: true
    working_dir: /src
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic:/usr/share/elasticsearch/data



